name: build OracleGraalVMEEJava
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - BellSoft-Liberica-java8/**
      - BellSoft-Liberica-java11/**
      - BellSoft-Liberica-java17/**
jobs:
  push:
    name: "yolks:bellsoft-liberica-java${{ matrix.tag }}/${{ matrix.arch }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '8'
          - '11'
          - '17'
        arch:
          - 'aarch64'
          - 'amd64'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUBTOKEN }}


      - name: Build&Push(aarch64)-Java17
        if: matrix.arch == 'aarch64' && matrix.tag == '17'
        uses: docker/build-push-action@v2
        with:
          context: ./BellSoft-Liberica-java${{ matrix.tag }}/aarch64
          file: ./BellSoft-Liberica-java${{ matrix.tag }}/aarch64/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/mg8853/yolks_aarch64:bellsoft-liberica-java${{ matrix.tag }}-aarch64
      - name: Build&Push(amd64)-Java17
        if: matrix.arch == 'amd64' && matrix.tag == '17'
        uses: docker/build-push-action@v2
        with:
          context: ./BellSoft-Liberica-java${{ matrix.tag }}/amd64
          file: ./BellSoft-Liberica-java${{ matrix.tag }}/amd64/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/mg8853/yolks_amd64:bellsoft-liberica-java${{ matrix.tag }}-amd64


      - name: Build&Push(aarch64)-Java11
        if: matrix.arch == 'aarch64' && matrix.tag == '11'
        uses: docker/build-push-action@v2
        with:
          context: ./BellSoft-Liberica-java${{ matrix.tag }}/aarch64
          file: ./BellSoft-Liberica-java${{ matrix.tag }}/aarch64/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/mg8853/yolks_aarch64:bellsoft-liberica-java${{ matrix.tag }}-aarch64
      - name: Build&Push(amd64)-Java11
        if: matrix.arch == 'amd64' && matrix.tag == '11'
        uses: docker/build-push-action@v2
        with:
          context: ./BellSoft-Liberica-java${{ matrix.tag }}/amd64
          file: ./BellSoft-Liberica-java${{ matrix.tag }}/amd64/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/mg8853/yolks_amd64:bellsoft-liberica-java${{ matrix.tag }}-amd64


      - name: Build&Push(aarch64)-Java8
        if: matrix.arch == 'aarch64' && matrix.tag == '8'
        uses: docker/build-push-action@v2
        with:
          context: ./BellSoft-Liberica-java${{ matrix.tag }}/aarch64
          file: ./BellSoft-Liberica-java${{ matrix.tag }}/aarch64/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/mg8853/yolks_aarch64:bellsoft-liberica-java${{ matrix.tag }}-aarch64
      - name: Build&Push(amd64)-Java8
        if: matrix.arch == 'amd64' && matrix.tag == '11'
        uses: docker/build-push-action@v2
        with:
          context: ./BellSoft-Liberica-java${{ matrix.tag }}/amd64
          file: ./BellSoft-Liberica-java${{ matrix.tag }}/amd64/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/mg8853/yolks_amd64:bellsoft-liberica-java${{ matrix.tag }}-amd64
