name: build mariadb
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - MariaDB-Arm/**
jobs:
  push:
    name: "yolks:mariadb_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '10.7'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUBTOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./MariaDB-Arm
          file: ./MariaDB-Arm/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/Docker-Repo/yolks:mariadb_${{ matrix.tag }}
