name: build OracleGraalVMEEJava
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - Oracle-GraalVM-EE-java8/**
      - Oracle-GraalVM-EE-java11/**
      - Oracle-GraalVM-EE-java17/**
jobs:
  push:
    name: "yolks:oracle-graalvm-ee-java${{ matrix.tag }}/${{ matrix.arch }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '8'
          - '11'
          - '17'
        arch:
          - 'arm'
          - 'amd'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUBTOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./Oracle-GraalVM-EE-java${{ matrix.tag }}/${{ matrix.arch }}
          file: ./Oracle-GraalVM-EE-java${{ matrix.tag }}/${{ matrix.arch }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/mg8853/yolks:oracle-graalvm-ee-java${{ matrix.tag }}
